@startuml
skinparam class {
    BackgroundColor #f0f0f0
    BorderColor #333333
    BorderThickness 1
}
entity "User" as Users {
    +userId: number <<generated>>
    --
    +username: String
    +email: String
    +password: String
    +phone_number: String
    +profile_image_url: String
    +created_at: DateTime
    +updated_at: DateTime
}
entity "Marker" as Markers {
    +locationId: number <<generated>>
    +userId: number <<FK>>
    --
    +name: String
    +description: String
    +latitude: Float
    +longitude: Float
    +created_at: DateTime
    +updated_at: DateTime
}
entity "MediaFile" as MediaFiles {
    +mediaId: <<generated>>
    +locationId: number <<FK>>
    +userId: number <<FK>>
    --
    +mediaType: String
    +mediaUrl: String
    +created_at: DateTime
    +updated_at: DateTime
}
entity "MapRoute" as MapRoutes {
    +routeId: <<generated>>
    +locationId: number <<FK>>
    +userId: number <<FK>>
    --
    +name: String
    +startMarker: String
    +endMarker: String
    +created_at: DateTime
    +updated_at: DateTime
}
entity "Owl" as Owls {
    +owlId: <<generated>>
    +locationId: number <<FK>>
    --
    +name: String
    +description: String
    +species: enum
    +created_at: DateTime
    +updated_at: DateTime
}
Users }o-u-o{ Markers : "many has many"
Users ||-r-o{ MediaFiles : "uploads"
Markers ||-r-o{ MediaFiles : "contains"
Markers ||-r-o{ Owls : "has"
Users ||-l-o{ MapRoutes : "creates"
MapRoutes ||-u-o{ Markers : "includes"
@enduml
